workspace:
  base: /go
  path: src/github.com/bitlogic/gitlab-ssh

pipeline:
  build:
    image: bitlogicos/btools
    commands:
      - govendor sync
      - govendor build
    when:
      local: true

  publish:
    image: plugins/docker
    repo: bitlogicos/gitlab-ssh
    file: Dockerfile
    tag:
      - latest
      - "1.0.${DRONE_BUILD_NUMBER}"
    secrets: [ docker_username, docker_password ]
    when:
      local: true